/* make-eco.js — turns the lichess-org/chess-openings dataset (CC0,
   public domain: https://github.com/lichess-org/chess-openings) into
   chess/eco.js, our full opening-name table. Every line is replayed
   through the engine before it may ship: an illegal or non-canonical
   move aborts the build.

   Run:  node chess/tools/make-eco.js [dir-with-a..e.tsv]
   With no argument it downloads the five TSVs from GitHub. */
"use strict";
const fs = require("fs");
const path = require("path");
const https = require("https");
const Chess = require("../engine.js");

const FILES = ["a", "b", "c", "d", "e"];
const RAW = "https://raw.githubusercontent.com/lichess-org/chess-openings/master/";

function fetchText(url) {
  return new Promise((res, rej) => {
    https.get(url, (r) => {
      if (r.statusCode !== 200) return rej(new Error(url + " -> " + r.statusCode));
      let d = "";
      r.on("data", (c) => (d += c));
      r.on("end", () => res(d));
    }).on("error", rej);
  });
}

(async () => {
  const dir = process.argv[2];
  let rows = [];
  for (const f of FILES) {
    const text = dir
      ? fs.readFileSync(path.join(dir, f + ".tsv"), "utf8")
      : await fetchText(RAW + f + ".tsv");
    const lines = text.split("\n").slice(1); /* drop the header */
    for (const line of lines) {
      const cols = line.split("\t");
      if (cols.length < 3 || !cols[0].trim()) continue;
      rows.push({ eco: cols[0].trim(), name: cols[1].trim(), pgn: cols[2].trim() });
    }
  }

  /* validate every line through the engine and keep engine-canonical SAN */
  let bad = 0;
  const out = [];
  for (const r of rows) {
    const sans = r.pgn.replace(/\d+\.(\.\.)?/g, " ").trim().split(/\s+/);
    const g = Chess.create();
    let ok = true, canon = [];
    for (const s of sans) {
      const m = Chess.fromSAN(g, s);
      if (!m) { console.error("ILLEGAL:", r.eco, r.name, "at", s, "in", r.pgn); ok = false; bad++; break; }
      canon.push(Chess.play(g, m));
    }
    if (ok) out.push(r.eco + "\t" + r.name + "\t" + canon.join(" "));
  }
  if (bad) { console.error(bad + " bad line(s) — refusing to write eco.js"); process.exit(1); }

  const packed = out.join("\n");
  const js = `/* eco.js — the full opening-name table: ${out.length} lines from the
   lichess-org/chess-openings dataset (CC0 public domain,
   https://github.com/lichess-org/chess-openings), each one replayed and
   verified by our engine at build time. Generated by tools/make-eco.js
   — edit the generator, not this file.

   Where book.js carries the *teaching* (ideas and per-move reasons for
   the great openings), this table carries the *naming*: whatever two
   players wander into, the room can usually tell them what the world
   calls it. */
(function (root) {
"use strict";
var DATA = ${JSON.stringify(packed)};
var lines = null;
var bySeq = null;
function init() {
  if (lines) return;
  lines = [];
  bySeq = {};
  var rows = DATA.split("\\n");
  for (var i = 0; i < rows.length; i++) {
    var c = rows[i].split("\\t");
    var entry = { eco: c[0], name: c[1], seq: c[2] };
    lines.push(entry);
    bySeq[c[2]] = entry;
  }
}
/* deepest named position along the played moves (sans: array of SAN
   with +/# suffixes allowed) */
function match(sans) {
  init();
  var clean = [];
  for (var i = 0; i < sans.length && i < 36; i++) clean.push(sans[i].replace(/[+#]$/, ""));
  for (var k = clean.length; k >= 1; k--) {
    var hit = bySeq[clean.slice(0, k).join(" ")];
    if (hit) return hit;
  }
  return null;
}
/* named continuations one move deeper than the current sequence */
function next(sans) {
  init();
  var clean = [];
  for (var i = 0; i < sans.length; i++) clean.push(sans[i].replace(/[+#]$/, ""));
  var prefix = clean.join(" ");
  var seen = {}, out = [];
  for (var j = 0; j < lines.length; j++) {
    var l = lines[j];
    if (prefix && l.seq.lastIndexOf(prefix + " ", 0) !== 0) continue;
    if (!prefix && l.seq.indexOf(" ") >= 0) { /* first move: any line qualifies */ }
    var rest = prefix ? l.seq.slice(prefix.length + 1) : l.seq;
    var move = rest.split(" ")[0];
    if (!move) continue;
    if (seen[move] === undefined) { seen[move] = out.length; out.push({ san: move, name: l.name, eco: l.eco }); }
  }
  return out;
}
var Eco = { match: match, next: next, count: function () { init(); return lines.length; } };
if (typeof module !== "undefined" && module.exports) module.exports = Eco;
else root.Eco = Eco;
})(typeof self !== "undefined" ? self : this);
`;
  fs.writeFileSync(path.join(__dirname, "..", "eco.js"), js);
  console.log("eco.js written:", out.length, "lines,", Math.round(js.length / 1024) + "KB");
})().catch((e) => { console.error(e); process.exit(1); });
