/* make-tactics.js — turns the lichess puzzle database (CC0 public
   domain, https://database.lichess.org/#puzzles) into chess/tactics.js,
   a small curated tactics pack for a future "puzzles" mode.

   The full dump is ~5 million puzzles; this keeps a few hundred
   beginner-friendly ones (popular, gently rated, classic themes) and
   — in the house manner — replays every single one through the engine
   before it may ship: the setup FEN must load, every move must be
   legal, and a mate-themed puzzle must actually end in checkmate.

   Format note (their format, kept as-is): the FEN is the position
   *before* the opponent's move; Moves is UCI, and the FIRST move is
   the opponent's blunder, played automatically — the solver answers
   from move two.

   This sandbox's network can't reach database.lichess.org, so the data
   doesn't ship yet. On any machine that can:
     curl -O https://database.lichess.org/lichess_db_puzzle.csv.zst
     zstd -d lichess_db_puzzle.csv.zst
     node chess/tools/make-tactics.js lichess_db_puzzle.csv
   Run with a small fixture CSV to see the validation work. */
"use strict";
const fs = require("fs");
const path = require("path");
const readline = require("readline");
const Chess = require("../engine.js");

const SRC = process.argv[2];
if (!SRC) { console.error("usage: node chess/tools/make-tactics.js <lichess_db_puzzle.csv> [max]"); process.exit(1); }
const MAX = +(process.argv[3] || 400);
const WANT_THEMES = ["mateIn1", "mateIn2", "hangingPiece", "fork", "pin", "backRankMate"];
const MAX_RATING = 1400, MIN_POPULARITY = 85;

function uciToMove(g, uci) {
  const from = Chess.sqIndex(uci.slice(0, 2)), to = Chess.sqIndex(uci.slice(2, 4));
  const promoCh = uci[4];
  const all = Chess.moves(g);
  for (const m of all) {
    if (m.from !== from || m.to !== to) continue;
    if (promoCh) {
      const kind = { q: Chess.Q, r: Chess.R, b: Chess.B, n: Chess.N }[promoCh];
      if (Math.abs(m.promo) !== kind) continue;
    } else if (m.promo) continue;
    return m;
  }
  return null;
}

(async () => {
  const rl = readline.createInterface({ input: fs.createReadStream(SRC), crlfDelay: Infinity });
  let header = null, cols = {};
  const kept = [];
  let seen = 0, rejected = 0;
  for await (const line of rl) {
    if (!header) {
      header = line.split(",");
      header.forEach((h, i) => (cols[h] = i));
      for (const need of ["FEN", "Moves", "Rating", "Popularity", "Themes"]) {
        if (cols[need] === undefined) { console.error("missing column: " + need); process.exit(1); }
      }
      continue;
    }
    if (kept.length >= MAX) break;
    const c = line.split(",");
    if (c.length < header.length) continue;
    seen++;
    const rating = +c[cols.Rating], pop = +c[cols.Popularity];
    const themes = c[cols.Themes].split(" ");
    if (rating > MAX_RATING || pop < MIN_POPULARITY) continue;
    if (!themes.some((t) => WANT_THEMES.includes(t))) continue;

    /* replay it: setup, opponent's move, then the whole solution */
    const fen = c[cols.FEN], uc = c[cols.Moves].trim().split(" ");
    let g;
    try { g = Chess.create(fen); } catch (e) { rejected++; continue; }
    let ok = uc.length >= 2;
    for (const u of uc) {
      const m = ok && uciToMove(g, u);
      if (!m) { ok = false; break; }
      Chess.play(g, m);
    }
    if (ok && themes.some((t) => /^mateIn\d$/.test(t))) {
      const st = Chess.status(g);
      if (st.reason !== "checkmate") ok = false;
    }
    if (!ok) { rejected++; continue; }
    kept.push([fen, c[cols.Moves].trim(), rating, themes.filter((t) => WANT_THEMES.includes(t))[0]].join("|"));
  }

  const js = `/* tactics.js — ${kept.length} beginner tactics from the lichess puzzle
   database (CC0 public domain, https://database.lichess.org/#puzzles),
   every one replayed and verified by our engine at build time.
   Generated by tools/make-tactics.js — edit the generator, not this
   file. Row format: setupFEN|uciMoves|rating|theme (the first move is
   the opponent's, played automatically). */
(function (root) {
"use strict";
var DATA = ${JSON.stringify(kept.join("\n"))};
var Tactics = {
  all: function () {
    return DATA ? DATA.split("\\n").map(function (r) {
      var c = r.split("|");
      return { fen: c[0], moves: c[1].split(" "), rating: +c[2], theme: c[3] };
    }) : [];
  }
};
if (typeof module !== "undefined" && module.exports) module.exports = Tactics;
else root.Tactics = Tactics;
})(typeof self !== "undefined" ? self : this);
`;
  fs.writeFileSync(path.join(__dirname, "..", "tactics.js"), js);
  console.log(`tactics.js written: kept ${kept.length} of ${seen} scanned (${rejected} failed validation)`);
})();
