/* make-lessons.js — find a real position for every technique.

   The Dojo does not teach from hand-drawn diagrams. It teaches from
   positions that genuinely arose: this tool digs thousands of puzzles,
   solves each one technique by technique, and the first time a
   technique is the *simplest thing available*, it writes that moment
   down. A lesson is therefore two numbers and a puzzle:

       { tech: "xWing", puzzle: <81 chars>, skip: 14 }

   — solve `puzzle` with the normal solver, stop after `skip` steps, and
   the technique fires on what is in front of you. Nothing is stored
   that could drift out of step with the solver, because the solver
   itself reconstructs the moment.

   Run: node sudoku/tools/make-lessons.js  [--rounds=4000] [--seed=1]
   Writes sudoku/lessons.js. Every lesson is verified before it ships. */
"use strict";

var fs = require("fs"), path = require("path");
var dir = path.join(__dirname, "..");
var S = require(path.join(dir, "core.js"));
var Strat = require(path.join(dir, "strategies.js"));

var ROUNDS = 4000, SEED = 1, WANT = 3;      // positions per technique
process.argv.slice(2).forEach(function (a) {
  if (a.indexOf("--rounds=") === 0) ROUNDS = parseInt(a.slice(9), 10);
  if (a.indexOf("--seed=") === 0) SEED = parseInt(a.slice(7), 10);
  if (a.indexOf("--want=") === 0) WANT = parseInt(a.slice(7), 10);
});

var wanted = Strat.TECHS.filter(function (t) { return t.id !== "ariadne"; });
var found = {};
wanted.forEach(function (t) { found[t.id] = []; });

function range(n) { var a = []; for (var i = 0; i < n; i++) a.push(i); return a; }
function usedBy(list, puzzle) {
  return list.some(function (L) { return L.puzzle === puzzle; });
}
function complete() {
  return wanted.every(function (t) { return found[t.id].length >= WANT; });
}

var t0 = Date.now();

/* Two passes. The first only records a technique when it is the
   *simplest move on the board* — the honest lesson. The second, for
   whatever is still missing (a jellyfish is almost never the simplest
   move anywhere), takes the pattern wherever it occurs and marks the
   lesson `alt`, so the Dojo can say so out loud. */
for (var phase = 0; phase < 2; phase++) {
  for (var n = 0; n < ROUNDS && !complete(); n++) {
    var rnd = S.rng(SEED * 1000003 + phase * 7919 + n);
    var full = S.fullGrid(rnd), g = S.clone(full), order = S.shuffle(range(81), rnd);
    for (var k = 0; k < 81; k++) {
      var i = order[k], v = g[i]; g[i] = 0;
      if (S.countSolutions(g, 2) !== 1) g[i] = v;
    }
    var puzzle = S.toString(g);
    var st = Strat.state(g), guard = 0, skip = 0;
    while (guard++ < 400) {
      var step = Strat.nextStep(st, null);
      if (!step) break;
      var list = found[step.tech];
      /* One lesson per puzzle per technique, so the Dojo does not show
         the same grid three times with the pattern in a different corner. */
      if (list && list.length < WANT && skip < 60 && !usedBy(list, puzzle)) {
        list.push({ tech: step.tech, puzzle: puzzle, skip: skip });
      }
      if (phase === 1) {
        wanted.forEach(function (t) {
          if (t.id === step.tech || found[t.id].length >= WANT || t.tier < 2 || skip >= 60) return;
          if (usedBy(found[t.id], puzzle)) return;
          if (t.find(st)) found[t.id].push({ tech: t.id, puzzle: puzzle, skip: skip, alt: 1 });
        });
      }
      Strat.apply(st, step);
      skip++;
    }
  }
}

/* ---------- verify every lesson before it ships ---------- */
var lessons = [], missing = [];
wanted.forEach(function (t) {
  var list = found[t.id];
  if (!list.length) { missing.push(t.id); return; }
  list.forEach(function (L) {
    var g = S.fromString(L.puzzle), st = Strat.state(g);
    for (var s = 0; s < L.skip; s++) {
      var step = Strat.nextStep(st, null);
      if (!step) return;
      Strat.apply(st, step);
    }
    var here = Strat.BY_ID[t.id].find(st);
    if (!here) { console.log("  ! " + t.id + " did not reproduce — dropped"); return; }
    var sol = S.solve(g), sound = true;
    here.elim.forEach(function (e) { if (sol[e.i] === e.d) sound = false; });
    here.place.forEach(function (p) { if (sol[p.i] !== p.d) sound = false; });
    if (!sound) { console.log("  ! " + t.id + " position is unsound — dropped"); return; }
    lessons.push({ tech: t.id, puzzle: L.puzzle, skip: L.skip, alt: L.alt ? 1 : 0 });
  });
});

var byTech = {};
lessons.forEach(function (L) { (byTech[L.tech] || (byTech[L.tech] = [])).push(L); });

var out = [];
out.push("/* lessons.js — a real position for every technique.");
out.push("");
out.push("   GENERATED by tools/make-lessons.js — do not edit by hand.");
out.push("   Each entry is a puzzle and a number of solver steps: play the");
out.push("   puzzle forward that many steps with the normal solver and the");
out.push("   technique named is the simplest thing available on the board.");
out.push("   Every one was verified to reproduce and to be sound against the");
out.push("   brute-force answer at generation time, and again by");
out.push("   tools/selftest.js on every run. */");
out.push("(function (root) {");
out.push('"use strict";');
out.push("var LESSONS = {");
Object.keys(byTech).forEach(function (id, n, all) {
  var rows = byTech[id].map(function (L) {
    return '    { puzzle: "' + L.puzzle + '", skip: ' + L.skip + (L.alt ? ", alt: 1" : "") + " }";
  });
  out.push('  ' + JSON.stringify(id) + ": [");
  out.push(rows.join(",\n"));
  out.push("  ]" + (n === all.length - 1 ? "" : ","));
});
out.push("};");
out.push('if (typeof module !== "undefined" && module.exports) module.exports = LESSONS;');
out.push("else root.LESSONS = LESSONS;");
out.push('})(typeof self !== "undefined" ? self : this);');
out.push("");

fs.writeFileSync(path.join(dir, "lessons.js"), out.join("\n"));
console.log("wrote lessons.js — " + lessons.length + " positions across " +
            Object.keys(byTech).length + "/" + wanted.length + " techniques in " +
            Math.round((Date.now() - t0) / 1000) + "s");
if (missing.length) console.log("no position found for: " + missing.join(", "));
